### ISSUE TITLE
What are the prerequisites to run MLN_Generator?

### ISSUE THREAD

**Issue by vidhiJain** [sfu-cl-lab/MLN_Generator#8]
I ran the MLN_Generator for tutorial_Mondial dataset and obtained the following 

```
Start Writing MLN...
Writing Header...
Writing Rules..
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'tutorial_Mondial_BN.NumAttributes' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2728)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2678)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:894)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:732)
	at MLNExporter.Exporter.bodyBuilder(Exporter.java:272)
	at MLNExporter.Exporter.strBuilder(Exporter.java:422)
	at MLNExporter.Exporter.main(Exporter.java:53)
Finished Writing MLN...
```

The existence of `<dbName>_BN` database is not sufficient. A user must ensure that  `<dbName>_BN` database must contain table `NumAttributes` before one runs the `MLN_Generator`.

**Comment by vidhiJain** [comment]
I was running FactorBase.jar on tutorial_Mondial and obtained the following :-1: 
```
...
create table ForeignKeys_pvars as select * from  tutorial_Mondial_setup.ForeignKeys_pvars 
create table InputColumns as select * from  tutorial_Mondial_setup.InputColumns 
create table Attribute_Value as select * from  tutorial_Mondial_setup.Attribute_Value 
Exception in thread "main" com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '`d`-1' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1040)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)could
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2728)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2678)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:894)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:732)
	at lattice.short_rnid_LatticeGenerator.init(short_rnid_LatticeGenerator.java:148)
	at lattice.short_rnid_LatticeGenerator.generate(short_rnid_LatticeGenerator.java:59)
	at BayesBaseCT_SortMerge.buildCT(BayesBaseCT_SortMerge.java:68)
	at RunBB.runBBLearner(RunBB.java:40)
	at RunBB.main(RunBB.java:23)

```

**Duplicate entry '`d`-1' for key 'PRIMARY'** and **at lattice.short_rnid_LatticeGenerator.init(short_rnid_LatticeGenerator.java:148)** indicates that the problem could be in creating short relational node notation.  I am unable to find the duplicate entry `AttributeValue` table in `tutorial_Mondial_BN`.
